------------------JSON TO TABLE: BRIDGING UNSTRUCTURED AND STRUCTURED DATA----------------

---CREATING DATABASE NAME MINI PROJECT
CREATE DATABASE MINI_PROJECT
USE MINI_PROJECT

---CREATING TABLE FOR REFERRALS 
CREATE TABLE T_PC_REFERRALS
(
ID NVARCHAR(MAX)  ,
ENGAGEMENTID NVARCHAR(MAX)  ,
CREATEDDATETIME NVARCHAR(MAX)  ,
UPDATEDDATETIME NVARCHAR(MAX)  ,
EXPIRATIONDATETIME NVARCHAR(MAX)  ,
STATUS NVARCHAR(MAX)  ,
SUBSTATUS NVARCHAR(MAX)  ,
STATUSREASON NVARCHAR(MAX) ,
MPNID NVARCHAR(MAX)  ,
ACCEPTEDDATETIME NVARCHAR(MAX)  ,
ORGANIZATION_NAME NVARCHAR(MAX)  ,
ADDRESSLINE1 NVARCHAR(MAX)  ,
ADDRESSLINE2 NVARCHAR(MAX) ,
CITY NVARCHAR(MAX)  ,
STATE NVARCHAR(MAX) ,
COUNTRY NVARCHAR(MAX)  ,
POSTALCODE NVARCHAR(MAX)  ,
DEALVALUE NVARCHAR(MAX)  ,
CURRENCY NVARCHAR(MAX)  ,
FIRSTNAME NVARCHAR(MAX)  ,
LASTNAME NVARCHAR(MAX)  ,
MOBILENUMBER NVARCHAR(MAX)  ,
EMAIL NVARCHAR(MAX)  ,
ORG_DOMAIN NVARCHAR(MAX)  ,
DATAINSERTED DATETIME DEFAULT(GETDATE())
)

SELECT * FROM T_PC_REFERRALS

/*------------------------------[ADVENTUREWORKS2022]--------------------------------

USE [ADVENTUREWORKS2022]

THE ADVENTUREWORKS DATABASE IS A SAMPLE DATABASE PROVIDED BY MICROSOFT, COMMONLY
USED FOR DEMONSTRATING AND PRACTICING SQL SERVER FEATURES. IT REPRESENTS A FICTIONAL COMPANY
CALLED ADVENTURE WORKS CYCLES, A MANUFACTURER AND SELLER OF BICYCLES AND RELATED PRODUCTS. 
THE DATABASE IS DESIGNED TO SHOWCASE VARIOUS ASPECTS OF SQL SERVER, INCLUDING DATA MODELING, 
QUERYING, REPORTING, AND BUSINESS INTELLIGENCE.

KEY ASPECTS OF THE ADVENTUREWORKS DATABASE

BUSINESS DOMAIN:

COMPANY: ADVENTURE WORKS CYCLES.
INDUSTRY: MANUFACTURING AND SALES OF BICYCLES, COMPONENTS, AND ACCESSORIES.
OPERATIONS: THE DATABASE MODELS THE COMPANY'S OPERATIONS, INCLUDING PRODUCTION, 
SALES, PURCHASING, HUMAN RESOURCES, AND CUSTOMER MANAGEMENT.

DATABASE STRUCTURE:

TABLES: THE DATABASE CONTAINS SEVERAL TABLES ORGANIZED INTO DIFFERENT SCHEMAS THAT REPRESENT
DIFFERENT FUNCTIONAL AREAS OF THE BUSINESS.

PERSON: CONTAINS INFORMATION ABOUT PEOPLE, INCLUDING EMPLOYEES, CUSTOMERS, AND CONTACTS.

PRODUCTION: MANAGES DATA RELATED TO THE MANUFACTURING PROCESS, SUCH AS PRODUCT INFORMATION,
BILL OF MATERIALS, AND WORK ORDERS.

SALES: CONTAINS SALES ORDER INFORMATION, CUSTOMER DATA, SALES TERRITORY INFORMATION, AND SALES REPRESENTATIVES.

PURCHASING: MANAGES SUPPLIER INFORMATION, PURCHASE ORDERS, AND RELATED PURCHASING DATA.

HUMANRESOURCES: MANAGES EMPLOYEE DATA, DEPARTMENTS, AND JOB CANDIDATES.

WAREHOUSE: MANAGES DATA RELATED TO INVENTORY, STOCK LEVELS, AND LOCATIONS.

SCHEMAS: DIFFERENT FUNCTIONAL AREAS ARE ORGANIZED INTO SCHEMAS, SUCH AS PERSON,
PRODUCTION, SALES, PURCHASING, HUMANRESOURCES, AND WAREHOUSE.*/

--USING TABLES FROM ADVENTURES WORKS DATABASE FOR EXTRACTION OF SOME INFORMATION
